schema_version = "1.0.0"

id = "ColorSpaceConverter"
version = "1.0.0"
name = "Co.Space Converter"
tagline = "This is another extension"
maintainer = "Adriano de Regino <adrianoderegino@gmail.com>"
type = "add-on"


# website = "http://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

license = [
  "MIT License",
]
# Optional: required by some licenses.
copyright = [
  "2002-2024 Adriano de Regino",
  "1998 Company Name",